create extension if not exists pgcrypto;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', avatar_url text, height_cm numeric(5,1), current_weight_kg numeric(6,2), target_weight_kg numeric(6,2), training_goal text not null default 'Allgemeine Fitness', experience_level text not null default 'Anfänger', training_days_per_week smallint not null default 3 check (training_days_per_week between 1 and 7), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.exercises (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, name text not null, muscle_group text not null, equipment_type text not null, exercise_type text not null default 'Kraft', description text, instructions text[] not null default '{}', image_url text, is_public boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint public_exercise_owner check (not is_public or user_id is null));
create table public.workout_plans (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, muscle_groups text[] not null default '{}', estimated_minutes integer not null default 45 check (estimated_minutes between 5 and 600), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workout_plan_exercises (id uuid primary key default gen_random_uuid(), plan_id uuid not null references public.workout_plans(id) on delete cascade, exercise_id uuid not null references public.exercises(id) on delete restrict, sort_order integer not null default 0, sets integer not null check (sets > 0), reps integer not null check (reps > 0), weight_kg numeric(7,2) not null default 0, rest_seconds integer not null default 60 check (rest_seconds >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(plan_id,sort_order));
create table public.workout_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, plan_id uuid references public.workout_plans(id) on delete set null, plan_name text not null, status text not null default 'active' check(status in ('active','completed','abandoned')), started_at timestamptz not null default now(), completed_at timestamptz, duration_seconds integer not null default 0, total_volume_kg numeric(12,2) not null default 0, current_exercise_index integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workout_sets (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.workout_sessions(id) on delete cascade, exercise_id uuid not null references public.exercises(id) on delete restrict, set_number integer not null, planned_reps integer not null default 0, actual_reps integer not null default 0, weight_kg numeric(7,2) not null default 0, completed boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(session_id,exercise_id,set_number));
create table public.body_measurements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, measured_at timestamptz not null default now(), weight_kg numeric(6,2) not null check(weight_kg > 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.nutrition_goals (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, calories integer not null default 2000, protein_g integer not null default 150, carbs_g integer not null default 220, fat_g integer not null default 70, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.meals (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, eaten_at timestamptz not null default now(), calories integer not null default 0, protein_g numeric(7,2) not null default 0, carbs_g numeric(7,2) not null default 0, fat_g numeric(7,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.meal_entries (id uuid primary key default gen_random_uuid(), meal_id uuid not null references public.meals(id) on delete cascade, name text not null, amount_g numeric(8,2) not null default 0, calories integer not null default 0, protein_g numeric(7,2) not null default 0, carbs_g numeric(7,2) not null default 0, fat_g numeric(7,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.personal_records (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, exercise_id uuid references public.exercises(id) on delete set null, exercise_name text not null, weight_kg numeric(7,2) not null, achieved_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());

insert into public.exercises(id,name,muscle_group,equipment_type,exercise_type,description,instructions,image_url,is_public) values
('10000000-0000-4000-8000-000000000001','Ergometer','Beine','Cardio','Cardio','Gelenkschonendes Ausdauertraining und Warm-up.',array['Sattel passend einstellen','Ruhige Trittfrequenz halten'],'/assets/fitness/bike.jpeg',true),
('10000000-0000-4000-8000-000000000002','Laufband','Ganzkörper','Cardio','Cardio','Ausdauer, Intervalle und aktive Regeneration.',array['Aufrecht laufen','Tempo kontrolliert steigern'],'/assets/fitness/treadmill.jpeg',true),
('10000000-0000-4000-8000-000000000003','Kurzhantel-Bankdrücken','Brust','Kurzhantel','Kraft','Freies Drücken für Brust und Trizeps.',array['Schulterblätter zurückziehen','Hanteln kontrolliert senken'],'/assets/fitness/dumbbells.jpeg',true),
('10000000-0000-4000-8000-000000000004','Kurzhantel-Rack','Ganzkörper','Kurzhantel','Kraft','Freie Gewichte für vielseitiges Ganzkörpertraining.',array['Passendes Gewicht kontrolliert entnehmen','Kurzhanteln nach dem Training sicher zurücklegen'],'/assets/fitness/stairmaster.jpeg',true),
('10000000-0000-4000-8000-000000000005','Crunch-Maschine','Bauch','Maschine','Kraft','Geführte Rumpfbeugung für die Bauchmuskulatur.',array['Aus dem Bauch einrollen','Nacken neutral halten'],'/assets/fitness/crunch.jpeg',true),
('10000000-0000-4000-8000-000000000006','Beinbeuger','Beine','Maschine','Kraft','Isoliertes Training der hinteren Oberschenkel.',array['Polster oberhalb der Ferse','Hüfte stabil halten'],'/assets/fitness/legcurl.jpeg',true),
('10000000-0000-4000-8000-000000000007','Beinstrecker','Beine','Maschine','Kraft','Gezieltes Quadrizeps-Training.',array['Knieachse ausrichten','Endposition nicht einrasten'],'/assets/fitness/legextension.jpeg',true),
('10000000-0000-4000-8000-000000000008','Hackenschmidt-Kniebeuge','Beine','Maschine','Kraft','Geführte Kniebeuge für hohe Beinkraft.',array['Füße stabil platzieren','Knie folgen den Fußspitzen'],'/assets/fitness/hackenschmidt.jpeg',true),
('10000000-0000-4000-8000-000000000009','Rückenstrecker','Rücken','Maschine','Kraft','Kräftigt unteren Rücken und Gesäß.',array['Wirbelsäule neutral halten','Nur bis zur Körperlinie strecken'],'/assets/fitness/backextension.jpeg',true),
('10000000-0000-4000-8000-000000000010','Beinpresse','Beine','Maschine','Kraft','Schweres Beintraining mit stabiler Führung.',array['Rücken am Polster lassen','Knie kontrolliert beugen'],'/assets/fitness/legpress.jpeg',true);

create index exercises_user_idx on public.exercises(user_id); create index exercises_filter_idx on public.exercises(muscle_group,equipment_type); create index plans_user_idx on public.workout_plans(user_id,updated_at desc); create index plan_exercises_plan_idx on public.workout_plan_exercises(plan_id,sort_order); create index sessions_user_date_idx on public.workout_sessions(user_id,started_at desc); create index sets_session_idx on public.workout_sets(session_id); create index measurements_user_date_idx on public.body_measurements(user_id,measured_at); create index meals_user_date_idx on public.meals(user_id,eaten_at desc); create index records_user_date_idx on public.personal_records(user_id,achieved_at desc);

do $$ declare t text; begin foreach t in array array['profiles','exercises','workout_plans','workout_plan_exercises','workout_sessions','workout_sets','body_measurements','nutrition_goals','meals','meal_entries','personal_records'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy "profiles own" on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy "exercises read public or own" on public.exercises for select using(is_public or user_id=auth.uid());
create policy "exercises write own" on public.exercises for all using(user_id=auth.uid() and not is_public) with check(user_id=auth.uid() and not is_public);
create policy "plans own" on public.workout_plans for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "plan exercises through owner" on public.workout_plan_exercises for all using(exists(select 1 from public.workout_plans p where p.id=plan_id and p.user_id=auth.uid())) with check(exists(select 1 from public.workout_plans p where p.id=plan_id and p.user_id=auth.uid()));
create policy "sessions own" on public.workout_sessions for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "sets through owner" on public.workout_sets for all using(exists(select 1 from public.workout_sessions s where s.id=session_id and s.user_id=auth.uid())) with check(exists(select 1 from public.workout_sessions s where s.id=session_id and s.user_id=auth.uid()));
create policy "measurements own" on public.body_measurements for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "nutrition goals own" on public.nutrition_goals for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "meals own" on public.meals for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "meal entries through owner" on public.meal_entries for all using(exists(select 1 from public.meals m where m.id=meal_id and m.user_id=auth.uid())) with check(exists(select 1 from public.meals m where m.id=meal_id and m.user_id=auth.uid()));
create policy "records own" on public.personal_records for all using(user_id=auth.uid()) with check(user_id=auth.uid());

do $$ declare t text; begin foreach t in array array['profiles','exercises','workout_plans','workout_plan_exercises','workout_sessions','workout_sets','body_measurements','nutrition_goals','meals','meal_entries','personal_records'] loop execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',t,t); end loop; end $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name','')); insert into public.nutrition_goals(user_id) values(new.id); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.delete_current_user() returns void language plpgsql security definer set search_path=public as $$ begin delete from auth.users where id=auth.uid(); end $$;
revoke all on function public.delete_current_user() from public; grant execute on function public.delete_current_user() to authenticated;
