// This file is auto-generated by ./tools/generate-projects.mjs
export const projects = [
  {
    "slug": "demo-project",
    "title": "Kochwelt",
    "client": "",
    "year": 2025,
    "status": "Live",
    "type": "Website",
    "description": "Kurzbeschreibung",
    "stack": [
      "HTML",
      "CSS",
      "JS"
    ],
    "tags": [
      "Static"
    ],
    "links": {
      "live": "https://weblabdesign.ch/projects/Kochwelt/index.html",
      "repo": null
    },
    "image": "../projects/Kochwelt/Vorlage/mockup.png"
  },
  {
    "slug": "demo-project-2",
    "title": "Band Website",
    "client": "",
    "year": 2025,
    "status": "Live",
    "type": "Website",
    "description": "Kurzbeschreibung",
    "stack": [
      "HTML",
      "CSS",
      "JS"
    ],
    "tags": [
      "Static"
    ],
    "links": {
      "live": "https://weblabdesign.ch/projects/band-website/index.html",
      "repo": null
    },
    "image": "../projects/band-website/img/mockup.jpg"
  },
  {
    "slug": "demo-project-3",
    "title": "Sakura Rahmen",
    "client": "",
    "year": 2025,
    "status": "Live",
    "type": "Website",
    "description": "Kurzbeschreibung",
    "stack": [
      "HTML",
      "CSS",
      "JS"
    ],
    "tags": [
      "Static"
    ],
    "links": {
      "live": "https://weblabdesign.ch/projects/sakura-ramen-responsive/index.html",
      "repo": null
    },
    "image": "../projects/sakura-ramen-responsive/img/1_hero/JPG/hero_bg.jpg"
  }
];
