// This file is auto-generated by ./tools/generate-projects.mjs
export const projects = [
  {
    "slug": "demo-project",
    "title": "Demo Project",
    "client": "",
    "year": 2025,
    "status": "Live",
    "type": "Website",
    "description": "Kurzbeschreibung",
    "stack": [
      "HTML",
      "CSS",
      "JS"
    ],
    "tags": [
      "Static"
    ],
    "links": {
      "live": "https://example.com",
      "repo": null
    },
    "image": "../projects/Kochwelt/img/Rumpsteak.jpg"
  },
  {
    "slug": "demo-project-2",
    "title": "Demo Project",
    "client": "",
    "year": 2025,
    "status": "Live",
    "type": "Website",
    "description": "Kurzbeschreibung",
    "stack": [
      "HTML",
      "CSS",
      "JS"
    ],
    "tags": [
      "Static"
    ],
    "links": {
      "live": "https://example.com",
      "repo": null
    },
    "image": "../projects/band-website/img/mockup.jpg"
  },
  {
    "slug": "demo-project-3",
    "title": "Demo Project",
    "client": "",
    "year": 2025,
    "status": "Live",
    "type": "Website",
    "description": "Kurzbeschreibung",
    "stack": [
      "HTML",
      "CSS",
      "JS"
    ],
    "tags": [
      "Static"
    ],
    "links": {
      "live": "https://example.com",
      "repo": null
    },
    "image": null
  }
];
