import type {
  Exercise,
  FitnessStore,
  MuscleGroup,
  EquipmentType,
} from "../types";

const exercise = (
  id: string,
  name: string,
  muscleGroup: MuscleGroup,
  equipment: EquipmentType,
  image: string,
  description: string,
): Exercise => ({
  id,
  name,
  muscleGroup,
  equipment,
  exerciseType: equipment === "Cardio" ? "Cardio" : "Kraft",
  image,
  description,
  instructions: [
    "Bewegung kontrolliert beginnen",
    "Rumpf stabil halten",
    "Gewicht ohne Schwung zurückführen",
  ],
  isPublic: true,
});

export const defaultExercises: Exercise[] = [
  exercise(
    "ex-bike",
    "Ergometer",
    "Beine",
    "Cardio",
    "/assets/fitness/bike.jpeg",
    "Gelenkschonendes Ausdauertraining und Warm-up.",
  ),
  exercise(
    "ex-treadmill",
    "Laufband",
    "Ganzkörper",
    "Cardio",
    "/assets/fitness/treadmill.jpeg",
    "Ausdauer, Intervalle und aktive Regeneration.",
  ),
  exercise(
    "ex-dumbbell",
    "Kurzhantel-Bankdrücken",
    "Brust",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Freies Drücken für Brust und Trizeps.",
  ),
  exercise(
    "ex-stairs",
    "Kurzhantel-Rack",
    "Ganzkörper",
    "Kurzhantel",
    "/assets/fitness/stairmaster.jpeg",
    "Freie Gewichte für vielseitiges Ganzkörpertraining.",
  ),
  exercise(
    "ex-crunch",
    "Crunch-Maschine",
    "Bauch",
    "Maschine",
    "/assets/fitness/crunch.jpeg",
    "Geführte Rumpfbeugung für die Bauchmuskulatur.",
  ),
  exercise(
    "ex-legcurl",
    "Beinbeuger",
    "Beine",
    "Maschine",
    "/assets/fitness/legcurl.jpeg",
    "Isoliertes Training der hinteren Oberschenkel.",
  ),
  exercise(
    "ex-legextension",
    "Beinstrecker",
    "Beine",
    "Maschine",
    "/assets/fitness/legextension.jpeg",
    "Gezieltes Quadrizeps-Training.",
  ),
  exercise(
    "ex-hack",
    "Hackenschmidt-Kniebeuge",
    "Beine",
    "Maschine",
    "/assets/fitness/hackenschmidt.jpeg",
    "Geführte Kniebeuge für hohe Beinkraft.",
  ),
  exercise(
    "ex-back",
    "Rückenstrecker",
    "Rücken",
    "Maschine",
    "/assets/fitness/backextension.jpeg",
    "Kräftigt unteren Rücken und Gesäß.",
  ),
  exercise(
    "ex-legpress",
    "Beinpresse",
    "Beine",
    "Maschine",
    "/assets/fitness/legpress.jpeg",
    "Schweres Beintraining mit stabiler Führung.",
  ),
  exercise(
    "ex-row",
    "Kabelrudern",
    "Rücken",
    "Kabelzug",
    "/assets/fitness/dumbbells.jpeg",
    "Horizontaler Zug für Rücken und hintere Schulter.",
  ),
  exercise(
    "ex-press",
    "Schulterdrücken",
    "Schulter",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Vertikales Drücken für Schulter und Trizeps.",
  ),
  exercise(
    "ex-dips",
    "Dips",
    "Arme",
    "Körpergewicht",
    "/assets/fitness/dumbbells.jpeg",
    "Körpergewichtsübung für Trizeps und Brust.",
  ),
  exercise(
    "ex-bench-press",
    "Bankdrücken",
    "Brust",
    "Langhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Klassische Grundübung für Brust, Schulter und Trizeps.",
  ),
  exercise(
    "ex-incline-press",
    "Schrägbankdrücken",
    "Brust",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Drückübung mit Fokus auf die obere Brust.",
  ),
  exercise(
    "ex-chest-press",
    "Brustpresse",
    "Brust",
    "Maschine",
    "/assets/fitness/dumbbells.jpeg",
    "Geführtes Brusttraining mit stabiler Bewegung.",
  ),
  exercise(
    "ex-cable-fly",
    "Kabel-Flys",
    "Brust",
    "Kabelzug",
    "/assets/fitness/dumbbells.jpeg",
    "Kontrollierte Adduktion für eine starke Brustkontraktion.",
  ),
  exercise(
    "ex-push-up",
    "Liegestütze",
    "Brust",
    "Körpergewicht",
    "/assets/fitness/dumbbells.jpeg",
    "Vielseitige Druckübung für Brust, Schulter und Rumpf.",
  ),
  exercise(
    "ex-pull-up",
    "Klimmzüge",
    "Rücken",
    "Körpergewicht",
    "/assets/fitness/backextension.jpeg",
    "Vertikaler Zug für Latissimus und Arme.",
  ),
  exercise(
    "ex-lat-pulldown",
    "Latzug",
    "Rücken",
    "Kabelzug",
    "/assets/fitness/backextension.jpeg",
    "Geführter vertikaler Zug für einen breiten Rücken.",
  ),
  exercise(
    "ex-barbell-row",
    "Langhantelrudern",
    "Rücken",
    "Langhantel",
    "/assets/fitness/backextension.jpeg",
    "Freier horizontaler Zug für den gesamten Rücken.",
  ),
  exercise(
    "ex-one-arm-row",
    "Einarmiges Kurzhantelrudern",
    "Rücken",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Einseitiges Rückentraining mit großem Bewegungsumfang.",
  ),
  exercise(
    "ex-face-pull",
    "Face Pulls",
    "Schulter",
    "Kabelzug",
    "/assets/fitness/dumbbells.jpeg",
    "Zugbewegung für hintere Schulter und Schulterblattkontrolle.",
  ),
  exercise(
    "ex-squat",
    "Kniebeuge",
    "Beine",
    "Langhantel",
    "/assets/fitness/hackenschmidt.jpeg",
    "Grundübung für Oberschenkel, Gesäß und Rumpf.",
  ),
  exercise(
    "ex-deadlift",
    "Kreuzheben",
    "Ganzkörper",
    "Langhantel",
    "/assets/fitness/backextension.jpeg",
    "Komplexe Zugübung für die gesamte hintere Kette.",
  ),
  exercise(
    "ex-romanian-deadlift",
    "Rumänisches Kreuzheben",
    "Beine",
    "Langhantel",
    "/assets/fitness/legcurl.jpeg",
    "Hüftdominante Übung für Beinbeuger und Gesäß.",
  ),
  exercise(
    "ex-hip-thrust",
    "Hip Thrust",
    "Beine",
    "Langhantel",
    "/assets/fitness/legpress.jpeg",
    "Gezieltes Hüftstrecken mit Fokus auf das Gesäß.",
  ),
  exercise(
    "ex-bulgarian-split-squat",
    "Bulgarian Split Squat",
    "Beine",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Einbeinige Kniebeuge für Kraft und Stabilität.",
  ),
  exercise(
    "ex-lunges",
    "Ausfallschritte",
    "Beine",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Dynamisches einbeiniges Training für Beine und Gesäß.",
  ),
  exercise(
    "ex-calf-raise",
    "Wadenheben",
    "Beine",
    "Maschine",
    "/assets/fitness/legpress.jpeg",
    "Kontrolliertes Training der Wadenmuskulatur.",
  ),
  exercise(
    "ex-overhead-press",
    "Schulterdrücken",
    "Schulter",
    "Langhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Vertikale Grundübung für Schulter und Trizeps.",
  ),
  exercise(
    "ex-lateral-raise",
    "Seitheben",
    "Schulter",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Isolationsübung für die seitliche Schulter.",
  ),
  exercise(
    "ex-rear-delt-fly",
    "Reverse Flys",
    "Schulter",
    "Maschine",
    "/assets/fitness/dumbbells.jpeg",
    "Gezieltes Training der hinteren Schulter.",
  ),
  exercise(
    "ex-biceps-curl",
    "Bizeps-Curls",
    "Arme",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Klassische Armbeugung für den Bizeps.",
  ),
  exercise(
    "ex-hammer-curl",
    "Hammer Curls",
    "Arme",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Neutraler Griff für Bizeps und Unterarme.",
  ),
  exercise(
    "ex-triceps-pushdown",
    "Trizepsdrücken",
    "Arme",
    "Kabelzug",
    "/assets/fitness/dumbbells.jpeg",
    "Kontrollierte Ellenbogenstreckung am Kabelzug.",
  ),
  exercise(
    "ex-french-press",
    "French Press",
    "Arme",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Überkopfstrecken mit Fokus auf den langen Trizepskopf.",
  ),
  exercise(
    "ex-plank",
    "Unterarmstütz",
    "Bauch",
    "Körpergewicht",
    "/assets/fitness/crunch.jpeg",
    "Isometrische Rumpfübung für Stabilität und Körperspannung.",
  ),
  exercise(
    "ex-leg-raise",
    "Beinheben",
    "Bauch",
    "Körpergewicht",
    "/assets/fitness/crunch.jpeg",
    "Dynamische Rumpfübung mit Fokus auf den unteren Bauch.",
  ),
  exercise(
    "ex-russian-twist",
    "Russian Twists",
    "Bauch",
    "Körpergewicht",
    "/assets/fitness/crunch.jpeg",
    "Rotationsübung für die seitliche Rumpfmuskulatur.",
  ),
  exercise(
    "ex-cable-crunch",
    "Kabel-Crunches",
    "Bauch",
    "Kabelzug",
    "/assets/fitness/crunch.jpeg",
    "Belastbare Rumpfbeugung am Kabelzug.",
  ),
  exercise(
    "ex-burpee",
    "Burpees",
    "Ganzkörper",
    "Körpergewicht",
    "/assets/fitness/treadmill.jpeg",
    "Intensive Ganzkörperübung für Kraft und Ausdauer.",
  ),
];

const daysAgo = (days: number) =>
  new Date(Date.now() - days * 86400000).toISOString();
export const createDemoStore = (userId = "demo-user"): FitnessStore => ({
  profile: {
    id: userId,
    displayName: "Demo Athlet",
    heightCm: 178,
    currentWeightKg: 82,
    targetWeightKg: 78,
    goal: "Muskelaufbau",
    level: "Fortgeschritten",
    trainingDays: 5,
  },
  exercises: defaultExercises,
  plans: [
    {
      id: "plan-push",
      name: "Push Day",
      muscleGroups: ["Brust", "Schulter", "Arme"],
      estimatedMinutes: 65,
      updatedAt: new Date().toISOString(),
      exercises: [
        {
          id: "pe-1",
          exerciseId: "ex-dumbbell",
          order: 0,
          sets: 4,
          reps: 8,
          weightKg: 34,
          restSeconds: 90,
        },
        {
          id: "pe-2",
          exerciseId: "ex-press",
          order: 1,
          sets: 3,
          reps: 10,
          weightKg: 22,
          restSeconds: 75,
        },
        {
          id: "pe-3",
          exerciseId: "ex-dips",
          order: 2,
          sets: 3,
          reps: 12,
          weightKg: 0,
          restSeconds: 60,
        },
        {
          id: "pe-4",
          exerciseId: "ex-crunch",
          order: 3,
          sets: 3,
          reps: 15,
          weightKg: 35,
          restSeconds: 45,
        },
      ],
    },
  ],
  sessions: Array.from({ length: 12 }, (_, i) => ({
    id: `session-${i}`,
    planId: "plan-push",
    planName: "Push Day",
    status: "completed" as const,
    startedAt: daysAgo(i * 3 + 1),
    completedAt: daysAgo(i * 3 + 1),
    durationSeconds: 3150,
    totalVolumeKg: 3100 + i * 120,
    sets: [],
    currentExerciseIndex: 0,
  })),
  measurements: [
    90, 89, 88, 88, 87, 86, 85, 85, 84, 83, 83, 82, 81.5, 81.8, 82,
  ].map((weightKg, i) => ({
    id: `m-${i}`,
    measuredAt: daysAgo((14 - i) * 7),
    weightKg,
  })),
  records: [
    {
      id: "pr-1",
      exerciseName: "Kniebeuge",
      weightKg: 140,
      achievedAt: daysAgo(18),
    },
    {
      id: "pr-2",
      exerciseName: "Bankdrücken",
      weightKg: 105,
      achievedAt: daysAgo(9),
    },
    {
      id: "pr-3",
      exerciseName: "Kreuzheben",
      weightKg: 170,
      achievedAt: daysAgo(25),
    },
  ],
  nutritionGoal: { calories: 2600, proteinG: 180, carbsG: 290, fatG: 75 },
  meals: [
    {
      id: "meal-1",
      name: "Frühstück",
      eatenAt: new Date().toISOString(),
      calories: 620,
      proteinG: 42,
      carbsG: 72,
      fatG: 18,
    },
    {
      id: "meal-2",
      name: "Mittagessen",
      eatenAt: new Date().toISOString(),
      calories: 780,
      proteinG: 58,
      carbsG: 85,
      fatG: 22,
    },
  ],
});
