import type {
  Exercise,
  FitnessStore,
  MuscleGroup,
  EquipmentType,
} from "../types";

const exercise = (
  id: string,
  name: string,
  muscleGroup: MuscleGroup,
  equipment: EquipmentType,
  image: string,
  description: string,
): Exercise => ({
  id,
  name,
  muscleGroup,
  equipment,
  exerciseType: equipment === "Cardio" ? "Cardio" : "Kraft",
  image,
  description,
  instructions: [
    "Bewegung kontrolliert beginnen",
    "Rumpf stabil halten",
    "Gewicht ohne Schwung zurückführen",
  ],
  isPublic: true,
});

export const defaultExercises: Exercise[] = [
  exercise(
    "ex-bike",
    "Ergometer",
    "Beine",
    "Cardio",
    "/assets/fitness/bike.jpeg",
    "Gelenkschonendes Ausdauertraining und Warm-up.",
  ),
  exercise(
    "ex-treadmill",
    "Laufband",
    "Ganzkörper",
    "Cardio",
    "/assets/fitness/treadmill.jpeg",
    "Ausdauer, Intervalle und aktive Regeneration.",
  ),
  exercise(
    "ex-dumbbell",
    "Kurzhantel-Bankdrücken",
    "Brust",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Freies Drücken für Brust und Trizeps.",
  ),
  exercise(
    "ex-stairs",
    "Stairmaster",
    "Beine",
    "Cardio",
    "/assets/fitness/stairmaster.jpeg",
    "Intensive Ausdauer mit Fokus auf Beine und Gesäß.",
  ),
  exercise(
    "ex-crunch",
    "Crunch-Maschine",
    "Bauch",
    "Maschine",
    "/assets/fitness/crunch.jpeg",
    "Geführte Rumpfbeugung für die Bauchmuskulatur.",
  ),
  exercise(
    "ex-legcurl",
    "Beinbeuger",
    "Beine",
    "Maschine",
    "/assets/fitness/legcurl.jpeg",
    "Isoliertes Training der hinteren Oberschenkel.",
  ),
  exercise(
    "ex-legextension",
    "Beinstrecker",
    "Beine",
    "Maschine",
    "/assets/fitness/legextension.jpeg",
    "Gezieltes Quadrizeps-Training.",
  ),
  exercise(
    "ex-hack",
    "Hackenschmidt-Kniebeuge",
    "Beine",
    "Maschine",
    "/assets/fitness/hackenschmidt.jpeg",
    "Geführte Kniebeuge für hohe Beinkraft.",
  ),
  exercise(
    "ex-back",
    "Rückenstrecker",
    "Rücken",
    "Maschine",
    "/assets/fitness/backextension.jpeg",
    "Kräftigt unteren Rücken und Gesäß.",
  ),
  exercise(
    "ex-legpress",
    "Beinpresse",
    "Beine",
    "Maschine",
    "/assets/fitness/legpress.jpeg",
    "Schweres Beintraining mit stabiler Führung.",
  ),
  exercise(
    "ex-row",
    "Kabelrudern",
    "Rücken",
    "Kabelzug",
    "/assets/fitness/dumbbells.jpeg",
    "Horizontaler Zug für Rücken und hintere Schulter.",
  ),
  exercise(
    "ex-press",
    "Schulterdrücken",
    "Schulter",
    "Kurzhantel",
    "/assets/fitness/dumbbells.jpeg",
    "Vertikales Drücken für Schulter und Trizeps.",
  ),
  exercise(
    "ex-dips",
    "Dips",
    "Arme",
    "Körpergewicht",
    "/assets/fitness/dumbbells.jpeg",
    "Körpergewichtsübung für Trizeps und Brust.",
  ),
];

const daysAgo = (days: number) =>
  new Date(Date.now() - days * 86400000).toISOString();
export const createDemoStore = (userId = "demo-user"): FitnessStore => ({
  profile: {
    id: userId,
    displayName: "Demo Athlet",
    heightCm: 178,
    currentWeightKg: 82,
    targetWeightKg: 78,
    goal: "Muskelaufbau",
    level: "Fortgeschritten",
    trainingDays: 5,
  },
  exercises: defaultExercises,
  plans: [
    {
      id: "plan-push",
      name: "Push Day",
      muscleGroups: ["Brust", "Schulter", "Arme"],
      estimatedMinutes: 65,
      updatedAt: new Date().toISOString(),
      exercises: [
        {
          id: "pe-1",
          exerciseId: "ex-dumbbell",
          order: 0,
          sets: 4,
          reps: 8,
          weightKg: 34,
          restSeconds: 90,
        },
        {
          id: "pe-2",
          exerciseId: "ex-press",
          order: 1,
          sets: 3,
          reps: 10,
          weightKg: 22,
          restSeconds: 75,
        },
        {
          id: "pe-3",
          exerciseId: "ex-dips",
          order: 2,
          sets: 3,
          reps: 12,
          weightKg: 0,
          restSeconds: 60,
        },
        {
          id: "pe-4",
          exerciseId: "ex-crunch",
          order: 3,
          sets: 3,
          reps: 15,
          weightKg: 35,
          restSeconds: 45,
        },
      ],
    },
  ],
  sessions: Array.from({ length: 12 }, (_, i) => ({
    id: `session-${i}`,
    planId: "plan-push",
    planName: "Push Day",
    status: "completed" as const,
    startedAt: daysAgo(i * 3 + 1),
    completedAt: daysAgo(i * 3 + 1),
    durationSeconds: 3150,
    totalVolumeKg: 3100 + i * 120,
    sets: [],
    currentExerciseIndex: 0,
  })),
  measurements: [
    90, 89, 88, 88, 87, 86, 85, 85, 84, 83, 83, 82, 81.5, 81.8, 82,
  ].map((weightKg, i) => ({
    id: `m-${i}`,
    measuredAt: daysAgo((14 - i) * 7),
    weightKg,
  })),
  records: [
    {
      id: "pr-1",
      exerciseName: "Kniebeuge",
      weightKg: 140,
      achievedAt: daysAgo(18),
    },
    {
      id: "pr-2",
      exerciseName: "Bankdrücken",
      weightKg: 105,
      achievedAt: daysAgo(9),
    },
    {
      id: "pr-3",
      exerciseName: "Kreuzheben",
      weightKg: 170,
      achievedAt: daysAgo(25),
    },
  ],
  nutritionGoal: { calories: 2600, proteinG: 180, carbsG: 290, fatG: 75 },
  meals: [
    {
      id: "meal-1",
      name: "Frühstück",
      eatenAt: new Date().toISOString(),
      calories: 620,
      proteinG: 42,
      carbsG: 72,
      fatG: 18,
    },
    {
      id: "meal-2",
      name: "Mittagessen",
      eatenAt: new Date().toISOString(),
      calories: 780,
      proteinG: 58,
      carbsG: 85,
      fatG: 22,
    },
  ],
});
